### ISSUE TITLE
Test Stream Checklist

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#1116]
Here's the items I'd like to test @niktek:

- [x] General OBS settings and capture
- [x] Audio levels
- [x] Screen capture - getting a perfect 1920x1080 is gonna be a challenge
- [x] Recording using my camera - should be able to do this through OBS
- [x] Recording OTHER folk's cameras - probably capturing Zoom or [Streamyard](https://streamyard.com/)
- [x] Scenes for "starting soon", "BRB", etc
- [x] I'd like to test playing a pre-recorded video. Again aspect ratio may be wonky
- [x] Ensure my Stream Deck hotkeys are working as expected
- [x] Schedule the YouTube and Twitter streams ahead of time (update Discord events)
- [x] Close caption support on either stream source
- [x] Stream-safe music?

**Comment by endigo9740** [comment]
Reminder, to add a mod on Twitch you use `/mod {username}`

**Comment by endigo9740** [comment]
Add to YouTube Description:

Music from #Uppbeat (free for Creators!):
https://uppbeat.io/t/avbe/night-in-kyoto
License code: D0YTNLTLQD69K1L2

Music from #Uppbeat (free for Creators!):
https://uppbeat.io/t/prigida/moonshine
License code: OWLCPIPUFJGJHEAG

Music from #Uppbeat (free for Creators!):
https://uppbeat.io/t/prigida/picture-frames
License code: JT5SLI75YRAI9OIY

**Comment by endigo9740** [comment]
Unfortunately it looks like Twitch closed captioning is going to be a bit outside our scope here:
https://help.twitch.tv/s/article/guide-to-closed-captions?language=en_US

**Comment by endigo9740** [comment]
Given the complexity of streaming to multiple services at once we're going to opt for ONLY YouTube tomorrow. There will be not Twitch streams I'm afraid. Sorry if that affects anyone's plans! We love Twitch so perhaps we'll try to do an stream there at another point in the future.
