### ISSUE TITLE
NEXT: Tailwind Plugin

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2360]
This will act as a hub to centralize for this information.

## See Also

The following updates will likely need to be handled in coordination.

* https://github.com/skeletonlabs/skeleton/issues/1142
* https://github.com/skeletonlabs/skeleton/issues/2359

## Tailwind Directive Layers

- `base` - global styles, resets, etc
- `components` - for opt-in element styles, like `.btn`
- `utilities` - general purpose utility classes
- `variants` - to append new variants, like `hover:` and `md:`

## Maintainer Requests

The following requests are coming straight from the Skeleton team. These are highly likely be implemented:

- [x] Implement skeleton utility classes via `theme.extend` over standalone classes
- [x] Explore using `@apply` directly in the tailwind plugin's CSS-in-JS objects ([reference](https://twitter.com/adamwathan/status/1742248960843227567))
- [x] Reorganize current styles; distribute to Tailwind directive layers
- [x] Updated Tailwind > Blocks to something more akin to the [OpenAI cookbook](https://cookbook.openai.com/)
- [x] Update Chrome scrollbar styles to [new spec](https://developer.chrome.com/docs/css-ui/scrollbar-styling)
- [x] Update theme type definitions to support all changes (removing `properties_dark`, etc)
- [x] A fix for the OS dark mode setting. [See the issue outlined here](https://github.com/skeletonlabs/skeleton/issues/2359#issuecomment-1912633056).
- [x] Implement @AdrianGonz97 suggestion for a [simpler theme import method](https://github.com/skeletonlabs/skeleton/issues/2360#issuecomment-1894410516)
- [ ] @AdrianGonz97 please see @niktek [question regarding exec scripts here](https://github.com/skeletonlabs/skeleton/pull/2431#discussion_r1468276610)
- [x] ~~Aim to make `config.content` simpler for core/svelte/react ([reference](https://tailwindcss.com/docs/plugins#extending-the-configuration))~~ (wait until TW v4)

Design Tokens:

- [x] Revisit the `token` prefix/suffix concept after implementing with `theme.extend`
- [x] Design token background styles should follow [Material Design's naming scheme](https://m3.material.io/components/all-buttons) (ex: Ghost -> Tonal)
- [x] The concept of "Variants" should be revisited; consider folding these into design tokens
- [x] We need to make the concept of "color pairings" more clear; lots of confusion around these

Tailwind Components (aka "Elements")

> NOTE: expect many minor revisions to all element styles provided by Skeleton.

- [x] Revisit Input-Groups; these have never quite worked as expected
- [x] Revisit Button-Groups these have never quite worked as expected
- [x] The table component will be retired in favor of the Table elements; consider making this more piecemeal

Cookbook (replaces "Blocks")

- [x] Chat
- [x] Gradient Headings
- [x] Image Layouts
- [x] Scroll Containers

## Community Requests

The following requests have come from the community and are under consideration:

- [x] https://github.com/skeletonlabs/skeleton/issues/2301
- [x] https://github.com/skeletonlabs/skeleton/issues/2003
- [x] https://github.com/skeletonlabs/skeleton/discussions/2444
- ~~https://github.com/skeletonlabs/skeleton/issues/2167~~ (will not implement)

## Bugs and Issues

- [x] [Bug with select dropdown menus on Windows](https://github.com/skeletonlabs/skeleton/issues/2360#issuecomment-1984313916)
- [x] There's a display issue for App Headers + the lightmode Rose theme in the documentation
- [x] https://github.com/skeletonlabs/skeleton/issues/1789

## Feedback

If you have additional updates or requests for this feature, please do so in the comments section below.

**Comment by AdrianGonz97** [comment]
Follow-up after the discussion in this thread: https://discord.com/channels/1003691521280856084/1196891462302957608

A change we can do is to expose all of the preset themes in an ESM format (so that they are importable in the user's app) and change the plugin api that registers them.

So rather than doing this (current):
```ts
// tailwind.config.js

// user's custom themes
import { myCustomTheme1, myCustomTheme2 } from "./customThemes.js";

/** @type {import('tailwindcss').Config} */
export default {
	// ...
	plugins: [
		skeleton({
			themes: {
				custom: [
					myCustomTheme1,
					myCustomTheme2
				],
				preset: [
					{ name: 'crimson', enhancements: true },
					{ name: 'gold-nouveau', enhancements: true },
					{ name: 'hamlindigo', enhancements: true },
					{ name: 'modern', enhancements: true },
					{ name: 'rocket', enhancements: true },
					{ name: 'sahara', enhancements: true },
					{ name: 'seafoam', enhancements: true },
					{ name: 'skeleton', enhancements: true },
					{ name: 'vintage', enhancements: true },
					{ name: 'wintry', enhancements: true }
				]
			}
		})
	]
};
```

We can instead unify the api such that custom themes and presets are registered to the same interface (v3):
```ts
// tailwind.config.js

// they can all be imported via an import glob
import * as themes from "@skeletonlabs/skeleton/themes";
// or imported individually like so:
import { modern, rocket } from "@skeletonlabs/skeleton/themes";

// user's custom themes
import { myCustomTheme1, myCustomTheme2 } from "./customThemes.js";


/** @type {import('tailwindcss').Config} */
export default {
	// ...
	plugins: [
		skeleton({
			themes: [ 
				myCustomTheme1,
				myCustomTheme2,
				themes.crimson, 
				themes.goldNouveau, 
				themes.hamindigo,
				modern,
				rocket,
				// etc..
		})
	]
};
```

**Comment by endigo9740** [comment]
@AdrianGonz97 I love it. Huge quality of life improvement there because it's one less thing to think about. Themes are just themes. I've added it to the list in the OP.

**Comment by endigo9740** [comment]
@AdrianGonz97 I tried doing a quick find/replace of `:root` -> `:base`, but unfortunately it's not a drop in replacement. This will not work for our use case so I'm going to nix it from the list above.

Here's the results. It basically nukes all styles provided by our plugin:

![Screenshot 2024-01-26 at 11 35 27 AM](https://github.com/skeletonlabs/skeleton/assets/1509726/dbe16a8f-1156-4b77-ad39-6ab5b5cff211)

**Comment by AdrianGonz97** [comment]
@endigo9740 
> `:root` -> `:base`

 Just for clarity, did you change it to `:base` or `:host`? `:host` is the pseudo-class we'd want to change to.

**Comment by endigo9740** [comment]
Doh, I used `host`. Just a typo

**Comment by endigo9740** [comment]
The find/replace was still present in VS Code, so I can confirm it was `:host` I tested:

![Screenshot 2024-01-26 at 2 10 29 PM](https://github.com/skeletonlabs/skeleton/assets/1509726/a21eadd4-6dea-4c67-b21d-5f86f44b5a12)

**Comment by endigo9740** [comment]
BUG: Display issue to resolve in the plugin styles for the Select element: 

![image](https://github.com/skeletonlabs/skeleton/assets/1509726/5f7e2602-171e-4d68-a579-e80d1a0fc465)

**Comment by niktek** [comment]
In regards to the darkMode issue - basically we need TW to generate different sets of classes depending on the darkMode strategy selected  (also note that there has been an update https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually to the names). As this is a build time artefact and will be static for our end-users, we can create two TW configs [here](https://github.com/skeletonlabs/skeleton/blob/next/packages/skeleton/scripts/compile-css-to-js.ts#L31) for embedding into the package.

Then on end-user load of the skeleton plugin, we need to get the darkMode setting for their project and use that to determine which generated CSSinJS module we import to pass back to TW.

TW does not pass the full config settings to the plugins, either via withOptions or by destructuring the theme on plugin init.

Considering the myriad of project setups/frameworks/monorepos etc that could come into play to try and find the tailwind config file to then parse, the safest option I can see is to parse the callStack and get the calling file from there:

in `packages/skeleton/src/plugin/core.ts`
```js
export function getSkeletonClasses() {
	// try/catch because it will throw when generated-classes.js isn't generated yet
	try {
		const error = new Error();
		// Extract stack trace from the Error object
		const stackTrace = error.stack ?? 'not found';
		const regex = /at registerPlugins \(([^()]+?)\/node_modules/g;
		const match = regex.exec(stackTrace);
		let path = '';
		if (match) {
			path = match[1];
		}
		const config = readFileSync(path + '/tailwind.config.ts', 'utf-8');
		writeFileSync('/Users/Shared/blah.txt', path, 'utf-8');

		const { components, base } = require('./generated/generated-classes.cjs');
```
This returns an absolute path to the folder containing the tailwind.config for me on macOS node and bun.  It needs further testing on other platforms etc.

We should then be able to import/parse it and get the mode to then know which generated file to return from above.

Gut feeling says it would be bad to require() the users tailwind config in case of side  effects.  It is also not guaranteed to just be 'selector' | 'media' as can be seen [here](https://tailwindcss.com/docs/dark-mode#customizing-the-selector)
