### ISSUE TITLE
NEXT: Automated Testing

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#2363]
As part of Skeleton v3, we'll implement support for multiple frontend frameworks. We'll likely want to consolidate on a common and universal testing tool. For this we'll opt for Vitest.

## Tasks

- [x] Install and configure Vitest: https://vitest.dev/
- [x] Install and configure Testing Library: https://testing-library.com/docs/
- [x] Implement for React components library
- [x] Implement for Svelte components library

## Goal

See: https://github.com/skeletonlabs/skeleton/issues/150

We need to ensure we have an adequate depth and quality of test cases per component. This will make it easier to introduce new features, handle refactors, and of course improve general QA testing. With the ultimate goal of ensuring we have a set of simple and robust test cases that are not too rigid.

Some component design and features are still in flux, so aim to ensure that tests may need to be improved over time.

## References:

- [React + Vitest + Testing Library Guide](https://victorbruce82.medium.com/vitest-with-react-testing-library-in-react-created-with-vite-3552f0a9a19a)

## Feedback

If you have additional updates or requests for this feature, please do so in the comments section below.

**Comment by Hugos68** [comment]
I'd think [Testing Library](https://testing-library.com/docs/) will be beneficial for cross framework component testing because the sheer amount of frameworks they support. This will allow for a familliar testing API no matter what framework is being tested on.

**Comment by endigo9740** [comment]
Yeah that's been my though as well. We actually use Testing Library already. Though I really hate\ the name - it's so generic you can't google for anything you need! Grr! :D

**Comment by endigo9740** [comment]
See also type testing: https://youtu.be/mWK3Y_1kmaM?si=64rMT3KiSCz7MQ0p&t=29214

**Comment by endigo9740** [comment]
Svelte Testing Library maintainer @mcous has shared a super helpful audit of changes recommended when we return to Svelte component testing:

- https://github.com/skeletonlabs/skeleton/discussions/2891#discussioncomment-11127131
