### ISSUE TITLE
Polish Pass: Components & Actions

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#857]
> **Note** - the majority of updates are now complete, testing and feedback is now requested. If you can help please do!

Base on:
- https://github.com/skeletonlabs/skeleton/issues/782

The goal of this pass will be to improve, refine, and finalized all Svelte components and actions in Skeleton.

- [x] Fix and address known issues and bugs
- [x] Improve the current styles, minimize code, better handling of edge cases
- [x] Expand with new features as relevant
- [x] Ensure form components play well with `use:enchance` forms
- [x] Move `SvgIcons` component from `/lib` to `/docs` and remove from `index.ts`
- [x] Ensure Vitest test cases are passing
- [x] Implement type of `CssClasses` (or similar) to identify Tailwind style props for IntelliSense auto-suggestions.
- [x] Update the CLI template(s) per the new component updates

### Clipboard

- [x] Documentation improvements.

### Filters

- [x] Minor code refactor for filter action
- [x] BREAKING: the filter action now requires `#` (ex: `"#Apollo"`)
- [x] Interactive examples - can switch images
- [x] Documentation improvements.
- [x] "How it Works" section added

### Focus Trap

- [x] Code snippets improved on the doc page
- [x] Documentation added explaining how it works
- [x] Documentation expanded to cover Modal/Drawers

### Accordions

- [x] Rename `AccordionGroup` component to `Accordion` for library consistency
- [x] Refactored to drop Disclosure elements in favor of accessible markup
- [x] Enable slide open/close animations for accordion contents
- [x] Allow the Item open state behavior to be controlled with the `autocollapse` property
- [x] Improve documentation and examples

### App Bar

- [x] BREAKING: renamed prop `space` to `spacing` for library consistency
- [x] Refactor slots and props to allow for more configurations
- [x] Introduce a new and optional "headline" row
- [x] The design has been updated to be less opinionated by default
- [x] Main/top row is now grid-based, rather than using flexbox
- [x] Update documentation to show a variety of preset configurations

> NOTE: want the old shadow effect? Use `shadow="shadow-lg"`

### App Rail

- [x] Added a new `border` prop on the AppRail
- [x] Improved documentation in regards to anchor tiles
- [x] Documented the process of setting the active state

### App Shell

- [x] The `#page` region now reports the vertical scroll position via the `on:scroll` event.
- [x] Provided better visualization of the scrollable portion of the App Shell
- [x] Added a new `regionPage` prop for adding classes to the scrollable `#page` region 
- [x] Document how to setup a sticky `pageHeader` slot
- [x] Linked to responsive sidebar/drawer tutorial

### Avatars

- [x] Documented techniques to add interactive borders
- [x] Provided support for `style` attribute, this allows Skeleton filters via CSS

> NOTE: investigated the bug for off center initials ([reference](https://user-images.githubusercontent.com/85238383/213514129-02b607a1-ea43-453e-aba0-79c16ba6fe70.png)). Unfortunately I cannot pin down a fix. Per the settings provided this the SVG text SHOULD be centered. Could be a browser issue?

### Conic Gradients

- [x] Stops are now reactive and will update as the values change
- [x] Greatly improved the documentation, added new usage techniques
- [x] Added props for `regionCaption|Cone|Legend` to apply arbitrary region classes

### File Buttons

- [x] BREAKING: The `name` property is now required to support Svelte's native form submission.
- [x] The design has been updated to be less opinionated by default
- [x] Documentation has been expanded

### File Dropzone

> **Warning** BREAKING: This component has been completely rebuilt from the ground up.

- [x] BREAKING: The `name` property is now required to support Svelte's native form submission.
- [x] Improved the code, added more config options, easier to style
- [x] Redesigned the UI to be more visually appealling
- [x] The `disabled` attribute now has a visual affect on the input
- [x] Documentation has been expanded

### Input Chips

> **Warning** BREAKING: This component has been completely rebuilt from the ground up.

- [x] BREAKING: The `name` property is now required to support Svelte's native form submission.
- [x] Embeds a native `<select>` input to provide better support for native forms
- [x] UI redesign from the ground up, including animations
- [x] Supports disabled state, per ([#824](https://github.com/skeletonlabs/skeleton/issues/824))
- [x] Provide a `max` prop to limit the maximum chips allowed
- [x] Provide `minlength` and `maxlength` props to control input character length

### Listboxes

> **Warning** BREAKING: This component has been completely rebuilt from the ground up.

- [x] BREAKING: The `name` property is now required to support Svelte's native form submission.
- [x] By default uses `radio` inputs for single selection
- [x] Apply the `multiple` prop to convert this to a `checkbox` input
- [x] Update the custom modal example using a Listbox

> NOTE: tested replacing with native select[size/multiple], but Safari support just isn't there yet.

### Paginators

- [x] Minor improvements to documentation and the example

> NOTE: we may revisit this component when we return to data tables

### Progress Bars

- [x] BREAKING: Replace `label` with `labelledby`, we recommend a wrapping `<label>` as needed
- [x] Minor refactor to the component logic and template
- [x] The design has been updated to be less opinionated by default

> NOTE: Documented native alternative, added native progress bar styles to `forms.css`

### Progress Radials

- [x] BREAKING: Replace `label` with `labelledby`, we recommend a wrapping `<label>` as needed
- [x] The design has been updated to be less opinionated by default
- [x] Improved documentation and examples

### Radio Groups

> **Warning** BREAKING: This component has been completely rebuilt from the ground up.

- [x] BREAKING: The `name` property is now required to support Svelte's native form submission.
- [x] BREAKING: `borderSize/borderWidth` combined into singular `border` prop for library consistency. 
- [x] This component is now a wrapper around a native radio checkbox input.
- [x] Renamed `accent` prop to `active` for library consistency
- [x] The design has been updated to be less opinionated by default
- [x] Supports disabled state, per ([#824](https://github.com/skeletonlabs/skeleton/issues/824))

### Range Sliders

- [x] BREAKING: The `name` property is now required to support Svelte's native form submission.
- [x] Minor refactor and code adjustments
- [x] Improved documentation and examples
- [x] Documented current browser support (Safari not fully supported)

### Slide Toggles

- [x] BREAKING: The `name` property is now required to support Svelte's native form submission.
- [x] BREAKING: the `accent` property renamed to `active` for library consistency 
- [x] BREAKING: `borderSize/borderWidth` combined into singular `border` prop for library consistency. 
- [x] The design has been updated to be less opinionated by default
- [x] The `class` attribute is now correctly implemented on the parent element
- [x] Improved documentation and examples

> Note: we investigated switching to styled native input[checkbox] elements ([ala Daisy](https://daisyui.com/components/toggle/)), but found the a11y story lacking.

### Steppers

> **Warning** BREAKING: This component has been completely rebuilt from the ground up.

- [x] Features a new horizontal layout by (EXTREMELY) popular demand!
- [x] Most properties have been updated or modified.
- [x] Allows for all English wording to be overwritten (ex: button labels, "Step", etc)

> NOTE: No plans to support a vertical version at this time.

### Tabs

> **Warning** BREAKING: This component has been completely rebuilt from the ground up.

- [x] Now includes an optional "panel" slot to improve a11y, per ([#516](https://github.com/skeletonlabs/skeleton/issues/516))
- [x] Minor redesign with updated props, events, and settings
- [x] Icon position is now above the text label
- [x] Improved documentation and examples

> NOTE: can be used in place of a bottom navigation bar when customized. See the doc example.

### Tables

- [x] Reviewed a means to fix overlays (ex: tooltips) being clipped - NOTE: won't fix, see below
- [x] Minor documentation improvements

> NOTE: per the clipping issue, this is due to the wrapping `.table-container` using `overflow-x-auto` and `.table` using `.overflow-hidden`. These are required styles, so unfortunately I'm going to have to advise against using overlays within tables for now. This is generally bad UX, so please avoid it.

### Table of Contents

- [x] Added `spacing` prop to set vertical spacing between rows
- [x] Added a note pointing to the example on the docs for desktop users.

**Comment by endigo9740** [comment]
A new PR for this is available here:
https://github.com/skeletonlabs/skeleton/pull/862

Preview URL:
https://skeleton-docs-git-chore-component-actions-6f245c-skeleton-labs.vercel.app/actions/clipboard

**Comment by niktek** [comment]
Just one that came up in Discord:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/52020637/213867962-b00ee1f9-bfdb-45f3-bfd7-88a8fb13f7fb.png">

**Comment by Gilgames000** [comment]
Hi! Here are a couple of things I'd really love to see in Skeleton, if possible :)

- modal that doesn't automatically close when clicked outside ([example](https://daisyui.com/components/modal/#modal-using-label--hidden-checkbox))
- animated accordion when collapsing/expanding content ([example](https://daisyui.com/components/collapse/#custom-colors-for-collapse-that-works-with-checkbox))
- countdown component ([example](https://daisyui.com/components/countdown/))

I also included links to examples of what I mean, because sometimes it's hard to explain things just with words :P

**Comment by Sarenor** [comment]
Hey @Gilgames000!
Good news, the animated Accordion is going to be part of this issue you commented on and has already been completed. You can find a preview of it here: https://skeleton-docs-git-chore-component-actions-6f245c-skeleton-labs.vercel.app/components/accordions
The Modal is part of the next polishing issue, work on fleshing that out is currently ongoing here: https://github.com/skeletonlabs/skeleton/issues/782

And the countdown is a new component that you can put down in it's own issue similar to the autocomplete issue:
https://github.com/skeletonlabs/skeleton/issues/377

**Comment by endigo9740** [comment]
@Gilgames000 

> modal that doesn't automatically close when clicked outside

This will never be part of Skeleton. It's a dark pattern and bad accessibility. We covered this here:
https://github.com/skeletonlabs/skeleton/issues/385

> animated accordion when collapsing/expanding content

As Dom mentioned and linked above, this is done and will be part of the next release.

> countdown component

Not something we intend to cover, though we would welcome a PR if someone wished to build this. But we officially recommend this library if you need something like this.

https://svelte-animated-counter.vercel.app/

**Comment by endigo9740** [comment]
@riziles suggested a method to improve the modal scrollbars here. We'll investigate this when we get to Modals:
https://github.com/skeletonlabs/skeleton/issues/890

**Comment by piperun** [comment]
In the Stepper component documentation, it describes in the event tab, events that only exists for the `<Stepper>` component as being for the `<Step>` component.


a few changes to Stepper that would be nice to see:
- Customizable Next/Prev button where placement and events such as `on:next` `on:previous` would be nice to have
- Integrates easily with form actions / progressive enhance (enables multi-form stepper)
- Choice of where the stepper placement will be (top, bottom, left or right)

**Comment by endigo9740** [comment]
We've merged this into the `dev` branch to make this easier to test. I'd welcome volunteers from anyone willing and able - there's a ton of changes in this update and we need full top-to-bottom regression testing.

## How to Test

If possible, clone down the Skeleton project, checkout the `dev` branch, then run it in the local server. This provides the ideal way to review both code and the documentation at the same time.

If you do not have the means to do this, consider viewing the documentation from the following URL. This is still a valuable way to find visual issues or typos:
https://dev.skeleton.dev/

## What To Test

Every feature listed under the Svelte category from the doc site app rail. This includes ALL Actions and ALL Components. Start the top of the list and work your way down.

## What to Look For

Be watchful for the following:

- Typos or grammar issues in update documentation
- Ensure the basic features are working on your device/browser of choice
- Consider testing on multiple browsers/OS to ensure we catch issues for those channels
- Ensure the doc instruction is clear and makes sense
- Look for bugs, edge case issues, or generally things going wrong

## Where to Report issues

DO THAT HERE! You're welcome to ask questions here or on Discord, but please actually report the issues UNDER this ticket please!

Be aware this update WILL go live on February 7th, so the more issues we find and fix, the better!

Thanks for your help!

**Comment by Hugos68** [comment]
Unrelated/related, not sure but the on the accordions page the WAI-AIRA link leads to a 404 whilst it should probably go to: https://www.w3.org/WAI/ARIA/apg/patterns/accordion/
This also is an issue present in current version here but might aswell be fixed in this update

**Comment by endigo9740** [comment]
Thanks @Hugos68 this was fixed part of: https://github.com/skeletonlabs/skeleton/commit/cb6a6566ae49c25e84e5f254a5f35ae78b5110e6

**Comment by endigo9740** [comment]
Given this release is dropping tomorrow I'm going to go ahead and close this ticket. If new issues are found related to components, please create dedicated tickets for them from this point forward. Do not add them here. Thanks!
